Update 0-run

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,10 @@
 #!/bin/bash
-python3 $PYFILE
+
+# Check if the PYFILE environment variable is set
+if [ -z "$PYFILE" ]; then
+    echo "Error: The PYFILE environment variable is not set."
+    exit 1
+fi
+
+# Run the Python script with the file name stored in PYFILE
+python "$PYFILE"
